apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: phoenix-staging-infrastructure
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  source:
    repoURL: 'https://github.com/Pheonix-Hotel-Reservation/pheonix-booking-config-repo.git'
    targetRevision: main
    path: environments/staging
    directory:
      include: '{staging-gateway.yaml,staging-router-vs.yaml,staging-request-authentication.yaml,gateway-allow-health-checks.yaml}'
  destination:
    server: https://kubernetes.default.svc
    namespace: phoenix-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true