apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: phoenix-staging-set
  namespace: argocd
spec:
  # 1. Generator: Find all service directories under 'apps/'
  generators:
  - git:
      repoURL: 'https://github.com/Pheonix-Hotel-Reservation/pheonix-booking-config-repo.git'
      # CRITICAL FIX 1: Use 'revision' in the generator block to satisfy the controller
      revision: main 
      directories:
      - path: apps/*

  # 2. Template: The Application definition to be generated for each service
  template:
    metadata:
      name: 'phoenix-staging-{{path.basename}}'
      annotations:
        argocd.argoproj.io/sync-wave: "10"
    spec:
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: phoenix-staging

      sources:
        # Source 1: The Git Repo (Value Provider)
        - repoURL: 'https://github.com/Pheonix-Hotel-Reservation/pheonix-booking-config-repo.git'
          # CRITICAL FIX 2: Use the standard 'targetRevision' field here
          targetRevision: main 
          ref: values
        
        # Source 2: The Base Helm Chart (The Consumer)
        - repoURL: 'https://github.com/Pheonix-Hotel-Reservation/pheonix-booking-config-repo.git'
          targetRevision: main
          path: '{{path}}'
          helm:
            valueFiles:
              # 1. Load the Base Defaults (Correct: Simple relative path)
              - 'values.yaml'
              # 2. Load the Staging Overlays 
              - '$values/environments/staging/{{path.basename}}.yaml'

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ServerSideApply=true
