apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: phoenix-production-infrastructure
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  source:
    repoURL: 'https://github.com/Pheonix-Hotel-Reservation/pheonix-booking-config-repo.git'
    targetRevision: main
    path: environments/production
    directory:
      include: '{production-gateway.yaml,production-router-vs.yaml,production-request-authentication.yaml,prometheus-network-policy.yaml}'
  destination:
    server: https://kubernetes.default.svc
    namespace: phoenix-production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true