# 01-platform/secrets-vault/vault-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hashicorp-vault
  namespace: argocd 
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    # ⚠️ Sync Wave 4: Runs after Istio Gateway (Sync Wave 3) is ready.
    argocd.argoproj.io/sync-wave: "4" 
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: vault # Dedicated namespace for Vault
  source:
    repoURL: https://helm.releases.hashicorp.com  
    targetRevision: 0.27.0 # 🚨 ACTION: Specify a stable Vault version
    chart: vault
    helm:
      # 🔑 INLINE VALUES: Embedding all configurations directly
      values: |
        server:
          enabled: true
          # Use Integrated Storage (Raft) for persistence in the PoC
          dataStorage:
            enabled: true
            size: 2Gi 
            storageClass: standard 
          # Set initial resources
          resources:
            requests:
              cpu: "300m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
        injector:
          enabled: true
          image:
            tag: "1.7.0" # Match server version
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
