
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secret-store
  namespace: platform-system
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1              # <- change region as needed
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-creds
            key: accessKeyID
          secretAccessKeySecretRef:
            name: aws-creds
            key: secretAccessKey
