
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault
  namespace: platform-system
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore
  target:
    name: vaultkey 
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: "platform/vault/key"    # AWS Secrets Manager secret name
        property: "Vault"
