apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: phoenix-staging-router
  namespace: phoenix-staging # Deploy in the application namespace
spec:
  hosts:
    - "pheonix-staging.pheonix.live"
  gateways:
    - istio-ingress/staging-gateway # Binds to the new dedicated staging gateway
  http:
  
  # 1. Route for User Service (Highest Priority: Specific Path Match)
  - match:
    - uri:
        # CRITICAL: Match traffic starting with /api/user
        prefix: /api/users 
    route:
    - destination:
        host: user-service.phoenix-staging.svc.cluster.local # Internal FQDN
        port:
          number: 3001 # App's internal port
          
  - match:
    - uri:
        prefix: /api/header-test
    route:
    - destination:
        host: phoenix-staging-header-echo.phoenix-staging.svc.cluster.local
        port:
          number: 3000
  
  - match:
    - uri:
        prefix: /api/hotels
    route:
    - destination:
        host: hotel-service.phoenix-staging.svc.cluster.local
        port:
          number: 3002

  - match:
    - uri:
        prefix: /api/rooms
    route:
    - destination:
        host: room-service.phoenix-staging.svc.cluster.local
        port:
          number: 3003

  - match:
    - uri:
        prefix: /api/reservations
    route:
    - destination:
        host: reservation-service.phoenix-staging.svc.cluster.local
        port:
          number: 3004

  - match:
    - uri:
        prefix: /api/search
    route:
    - destination:
        host: search-service.phoenix-staging.svc.cluster.local
        port:
          number: 3006

  # 3. Catch-all for Root/Static Content
  - match:
    - uri:
        prefix: / 
    route:
    - destination:
        # You can point this to a static front-end service or another entry point
        host: frontend.phoenix-staging.svc.cluster.local
        port:
          number: 8080

    