# File: platform/monitoring/istio-podmonitor.yaml (Corrected)

apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: istio-mesh-monitor
  namespace: monitoring
  labels:
    release: monitoring-stack-kube-prom
spec:
  selector:
    matchLabels:
      security.istio.io/tlsMode: istio
  podMetricsEndpoints:
  - # REMOVE: name: istio-proxy  <-- THIS FIELD IS CAUSING THE ERROR
    path: /stats/prometheus
    port: istio-metrics      
    interval: 15s
    relabelings:
      - sourceLabels: [__meta_kubernetes_pod_container_name]
        action: keep
        regex: istio-proxy
      - sourceLabels: [__meta_kubernetes_pod_name]
        action: replace
        targetLabel: pod_name