apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: istio-mesh-monitor
  namespace: monitoring
  labels:
    release: monitoring-stack-kube-prom
spec:
  namespaceSelector:
    matchNames:
      - phoenix-staging
      - phoenix-production
  selector:
    matchLabels:
      security.istio.io/tlsMode: istio
  podMetricsEndpoints:
    - path: /stats/prometheus
      port: 15090          # Envoy admin /stats endpoint (envoy metrics)
      interval: 15s
      honorLabels: true
      scheme: http
    - path: /stats/prometheus
      port: 15020          # Istio agent /proxy-agent metrics (agent-level)
      interval: 15s
      honorLabels: true
      scheme: http
