# 01-platform/istio-gateway/istio-gateway-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-ingress-gateway
  namespace: argocd 
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    # ⚠️ Sync Wave 3: Runs after Istiod (Sync Wave 2) is ready.
    argocd.argoproj.io/sync-wave: "3" 
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system 
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.27.0 # Must match Istio Base/Istiod version
    chart: gateway
    helm:
      values: |
        gateways:
          istio-ingressgateway:
            service:
              type: LoadBalancer
              ports:
                # Standard HTTP port
                - port: 80
                  targetPort: 8080
                  name: http2
                # Standard HTTPS port
                - port: 443
                  targetPort: 8443
                  name: https
            replicaCount: 1 # Sufficient for a PoC
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
