# 01-platform/istio-base/istiod-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod-control-plane
  namespace: argocd 
  annotations:
    # ⚠️ Sync Wave 2: Runs after Istio CRDs (Sync Wave 1) are complete.
    argocd.argoproj.io/sync-wave: "2" 
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system 
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.27.0 # 🚨 ACTION: Must match Istio Base version (1.27.0)
    chart: istiod         
    helm:
      # ArgoCD mounts the Kustomization directory, allowing access to the local values file
      valueFiles:
        - istiod-values.yaml
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false # istio-base already created this
