# 01-platform/istio-base/istio-base-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-base-crds
  namespace: argocd 
  annotations:
    # ⚠️ Sync Wave 1: Ensures these foundational CRDs are the very first resources deployed.
    argocd.argoproj.io/sync-wave: "1" 
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system 
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts 
    targetRevision: 1.27.0 # 🚨 ACTION: Lock to a stable version
    chart: base          
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 
      - PrunePropagationPolicy=foreground 
      - ApplyOutOfSyncOnly=true
