# 01-platform/istio-base/istiod-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod-control-plane
  namespace: argocd 
  annotations:
    # ⚠️ Sync Wave 2: Runs after Istio CRDs (Sync Wave 1) are complete.
    argocd.argoproj.io/sync-wave: "2" 
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system 
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.27.0 # 🚨 ACTION: Must match Istio Base version (1.27.0)
    chart: istiod
    helm:
      # Custom values for the Istiod Helm Chart (inline to avoid multi-source complexity)
      values: |
        global:
          # Sets the default Istio revision for automatic sidecar injection
          defaultRevision: default
          # Set desired resource limits for stability
          resource:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi

        meshConfig:
          # Policy to enforce STRICT mTLS mesh-wide by default (Zero-Trust foundation)
          defaultConfig:
            # Disable Istio Proxy debug logging to reduce noise
            proxyMetadata:
              ISTIO_META_ISTIO_PROXY_DEFAULT_LOG_LEVEL: "warn"
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false # istio-base already created this
