# 01-platform/logging-opensearch/fluent-bit-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluent-bit
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    # ⚠️ Sync Wave 7: Runs at the same time as OpenSearch.
    argocd.argoproj.io/sync-wave: "7" 
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: logging # Same dedicated namespace as OpenSearch
  source:
    # Using the official Fluent Bit chart repository
    repoURL: https://fluent.github.io/helm-charts
    targetRevision: 0.53.0 # 🚨 ACTION: Use a stable chart version
    chart: fluent-bit
    helm:
      values: |
        # Configuration to forward logs to the OpenSearch service
        config:
          outputs: |
            [OUTPUT]
                Name opensearch
                Match *
                Host phoenix-opensearch-master-data
                Port 9200
                Index fluentbit
                Type fluentbit
                Log_Level info
                Suppress_Type_Name On
                # Fluent Bit needs to send the basic auth credentials for OpenSearch's security plugin
                HTTP_User admin
                HTTP_Passwd admin
                tls Off 
                tls.verify Off # CRITICAL: Disable TLS verification for PoC self-signed certificates
        
        # General configurations
        logLevel: info
        resources:
          requests:
            cpu: 10m
            memory: 50Mi

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
