apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  # CRITICAL: Name this Secret what the RabbitMQ Chart expects if possible, 
  # or use a standard name and update the chart config (see Step 2).
  name: rabbitmq-broker-creds 
  namespace: phoenix-staging 
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-cluster-store # Name of your ClusterSecretStore
    kind: ClusterSecretStore
  target:
    # This is the name of the Kubernetes Secret that will be created
    name: rabbitmq
    creationPolicy: Owner
  data:
    # Ensure these secret keys match what the RabbitMQ Pod expects
    - secretKey: rabbitmq-username 
      remoteRef:
        key: kv/data/secret/data/rabbitmq
        property: RABBITMQ_USER 
    - secretKey: rabbitmq-password
      remoteRef:
        key: kv/data/secret/data/rabbitmq
        property: RABBITMQ_PASS