{{- if .Values.userSetupJob.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "rabbitmq.fullname" . }}-user-setup
  namespace: {{ .Release.Namespace }}
  annotations:
    # CRITICAL: Run this job *after* the StatefulSet is ready
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "5"
  labels:
    {{- include "rabbitmq.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      labels:
        {{- include "rabbitmq.labels" . | nindent 8 }}
    spec:
      restartPolicy: OnFailure
      containers:
        - name: configure-user
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            # Point to the running RabbitMQ node for command execution
            - name: RABBITMQ_NODE_IP_ADDRESS
              value: "127.0.0.1"
            - name: RABBITMQ_NODE_PORT
              value: "5672"
            # Inject credentials from the K8s Secret created by ESO
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.auth.existingSecret }} 
                  key: rabbitmq-username 
            - name: RABBITMQ_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.auth.existingSecret }} 
                  key: rabbitmq-password 
          command: ["/bin/bash", "-c"]
          args:
            - |
              # Wait for the main broker service to respond
              until rabbitmqctl status >/dev/null 2>&1; do 
                echo "Waiting for RabbitMQ broker to fully start..."
                sleep 5; 
              done
              
              echo "Broker is ready. Creating user $RABBITMQ_USER..."
              
              # 1. Add the user (uses the password from the secret)
              rabbitmqctl add_user $RABBITMQ_USER $RABBITMQ_PASS
              
              # 2. Set the management tags (CRITICAL for Web UI login)
              rabbitmqctl set_user_tags $RABBITMQ_USER administrator management
              
              # 3. Set the full permissions
              rabbitmqctl set_permissions -p / $RABBITMQ_USER ".*" ".*" ".*"
              
              echo "User configuration complete. Deleting job..."
{{- end }}