apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: rabbitmq-vs
  # Namespace is determined by the ApplicationSet deployment (e.g., phoenix-staging)
spec:
  hosts:
    - "rabbitmq.{{ .Release.Namespace }}.phoenix-project.online" # e.g., rabbitmq.phoenix-staging.phoenix-project.online
  gateways:
    - istio-ingress/staging-gateway
  http:
  # Enforce redirect for all traffic
  - match:
    - uri:
        prefix: /
      port: 80
    redirect:
      scheme: https
      port: 443
  # Route HTTPS to the Management UI port (15672)
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        # FQDN of the service created by the dependency chart
        host: phoenix-staging-rabbitmq-rabbitmq-broker.{{ .Release.Namespace }}.svc.cluster.local 
        port:
          number: 15672
