apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: user-service-jwt-required
  namespace: {{ .Release.Namespace }} 
spec:
  selector:
    matchLabels:
      app: user-service
  action: ALLOW
  rules:
  
  # Rule 1: Admin-only access to GET /
  - from:
    - source:
        requestPrincipals: ["*"]
    to:
    - operation:
        methods: ["GET"]
        paths: ["/"]
    when:
    - key: request.auth.claims[groups]
      values: ["*admin*"]  # Matches any groups claim containing "admin"
  
  # Rule 2: Any authenticated user access to ID-based endpoints
  - from:
    - source:
        requestPrincipals: ["*"]
    to:
    - operation:
        methods: ["GET", "POST", "PUT", "DELETE", "PATCH"]
        # Matches paths like /123, /abc123, /user123/loyalty-points, etc.
        # but NOT the root path /
        paths: ["/*"]
    when:
    - key: request.url_path
      notValues: ["/"]  # Exclude the root path from this rule