apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: user-service-jwt-required
  namespace: {{ .Release.Namespace }} 
spec:
  selector:
    matchLabels:
      app: user-service
  action: ALLOW
  rules:

  - to:
  - operation:
      methods: ["GET"]
      paths: ["/health", "/healthz", "/ready", "/alive", "/metrics"]
  
  # Rule 1: Admin-only access to GET /
  - from:
    - source:
        requestPrincipals: ["*"]
    to:
    - operation:
        methods: ["GET"]
        paths: ["/"]
    when:
    - key: request.auth.claims[groups]
      values: ["*admin*"]
  
  # Rule 2: Any authenticated user access to specific patterns
  - from:
    - source:
        requestPrincipals: ["*"]
    to:
    - operation:
        methods: ["GET", "POST", "PUT", "DELETE", "PATCH"]
        # Explicitly match the patterns you want to allow
        paths: 
        - "/[0-9]*"              # Matches /123, /456, etc. (numeric IDs)
        - "/[a-zA-Z0-9]*"        # Matches /abc123, /user456, etc. (alphanumeric IDs)
        - "/*/loyalty-points"     # Matches /:id/loyalty-points
        - "/asgardeo/*"          # Matches /asgardeo/:asgardeoId