apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: user-service-jwt-required
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: user-service
  action: ALLOW
  rules:
  
  # Rule 2: Admin-only access to GET /api/users/
  # - to:
  #   - operation:
  #       methods: ["GET"]
  #       paths: ["/api/users/"]
  #   when:
  #   - key: request.headers[x-auth-user-groups]
  #     values: ["*admin*"]
  
  # Rule 3: Authenticated users for specific endpoints
  - to:
    - operation:
        methods: ["GET", "POST", "PUT", "DELETE"]
        # paths: 
        # - "/api/users/[0-9]*"
        # - "/api/users/profile"
        # - "/api/users/*/loyalty-points"
        # - "/api/users/asgardeo/*"
    when:
    - key: request.headers[x-auth-user-id]
      values: ["*"]