apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: user-service-jwt-required
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: user-service
  action: ALLOW

  rules:
  - from:
    - source:
        principals: ["*"]          # must be authenticated
    to:
    - operation:
        methods: ["GET"]
        paths: ["/api/users/"]
    when:
    - key: "request.headers[x-auth-user-groups]"   # match the 'groups' claim
      values: ["admin"]                    # prefer exact match; change if IdP uses a different value

  # 3) All authenticated callers may use GET/POST/PUT/DELETE on any path
  - from:
    - source:
        principals: ["*"]
    to:
    - operation:
        methods: ["GET","POST","PUT","DELETE"]
        paths: 
        - "/api/users/[0-9]*"              # /api/users/123
        - "/api/users/profile"             # /api/users/profile
        - "/api/users/*/loyalty-points"    # /api/users/123/loyalty-points
    when:
    - key: request.headers[x-auth-user-id]
      notValues: [""]
