apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: user-service
  labels:
    # CRITICAL: This label must match the selector used by your Prometheus instance
    release: monitoring-stack-kube-prom
    app.kubernetes.io/part-of: monitoring-stack 
spec:
  selector:
    matchLabels:
      app: user-service # Selects the user-service K8s Service
  endpoints:
  - port: http-app # Application port
    path: /metrics # Application metrics endpoint
    interval: 30s
    scheme: http
