apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: user-service
  labels:
    # CRITICAL: This label must match the selector used by your Prometheus instance
    release: monitoring-stack-kube-prom
    app.kubernetes.io/part-of: monitoring-stack 
spec:
  selector:
    matchLabels:
      app: user-service # Selects the user-service K8s Service
  endpoints:
  - targetPort: 15020 # Istio proxy metrics port
    path: /stats/prometheus # Istio proxy Prometheus metrics endpoint
    interval: 30s
    scheme: http
    relabelings:
      # Only scrape metrics from the istio-proxy container
      - sourceLabels: [__meta_kubernetes_pod_container_name]
        action: keep
        regex: istio-proxy
